import "./globals.css";
import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Image from "next/image";
import Hamburger from "@/components/Hamburger";
import SerceIcon from "@/public/icons/serce-icon.svg";
import CartIcon from "@/public/icons/cart.svg";
import UserIcon from "@/public/icons/user.svg";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <div className="mx-4 mb-1">
          <nav className="flex items-center my-9 mx-1 gap-4">
            <Hamburger />
            <button className="ml-auto">
              <Image src={SerceIcon} alt="save" width={32} height={30} />
            </button>
            <button>
              <Image
                src={CartIcon}
                alt="dodaj do koszyka"
                width={37}
                height={25}
              />
            </button>
            <button>
              <Image src={UserIcon} alt="User icon" width={26} height={25} />
            </button>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
